package com.payflow.enums;

public enum AuditAction {
    CREATE, READ, UPDATE, DELETE, LOGIN, LOGOUT,
    PAYMENT_CREATED, PAYMENT_PROCESSED, REFUND_INITIATED,
    FRAUD_FLAGGED, WEBHOOK_SENT, RATE_LIMIT_HIT
}
